---
graphiti_base_url: http://graphiti.climatedna.net
graphite_base_url: http://graphite.integration.climatedna.net

redis_url: localhost:6379:1/graphiti
tmp_dir: /wb/tmp
fonts:
  - DroidSans
  - DejaVuSans
auto_refresh:
  enabled: true # checked by default?
  interval: 60 # seconds
default_options:
  title: "New Graph"
  from: -7d
  font: DroidSans
  fontSize: 10
  thickness: 2
  bgcolor: "#FFFFFF"
  fgcolor: "#333333"
  majorGridLineColor: "#ADADAD"
  minorGridLineColor: "#E5E5E5"
default_metrics:
  - "stats.timers.production.rails.controller.total.mean"
metric_prefix: ""
# Configure a service for snapshoting graphs. Current options are
# s3 (amazon s3) and fs (filesystem)
snapshots:
  # for s3 you need to provide `bucket`, `access_key_id`, and `secret_access_key`
  #
  # service: s3
  # bucket: mysnapshots
  # access_key_id: BLAH
  # secret_access_key: BLAHBLAH

  # for local filesystem you need to provide a dir to save the images
  # and the public route to that dir
  #
  service: fs
  dir: /wb/
  public_host: http://graphiti.local/storage

# These are options that are passed to Pony
# https://github.com/benprew/pony
# in `to:` SLUG gets replaced with the slug of the dashboard being sent
# reports:
#   from: "alice <alice@climate.com>"
#   to: "graphiti+SLUG@climate.com"
#   via: smtp
#   via_options:
#     address: 'smtp.gmail.com'
#     port: 587
#     authentication: plain
#     enable_starttls_auto: true,
#     user_name: ""
#     password: "PASSWORD"
